// <auto-generated />
using System;
using CDCNPM_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDCNPM_FInal.Migrations
{
    [DbContext(typeof(KaraokeContext))]
    [Migration("20191024173916_H")]
    partial class H
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDCNPM_FInal.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Avatar");

                    b.Property<decimal>("Balance");

                    b.Property<DateTime?>("BirthDay");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Booking", b =>
                {
                    b.Property<string>("BookingID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CusName");

                    b.Property<string>("CusPhone");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("EndTime");

                    b.Property<double>("PreMoney");

                    b.Property<int?>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("Status");

                    b.Property<double>("Total");

                    b.Property<string>("Username");

                    b.HasKey("BookingID");

                    b.HasIndex("RoomID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.DetailService", b =>
                {
                    b.Property<string>("BookingID");

                    b.Property<string>("ServiceID");

                    b.HasKey("BookingID");

                    b.HasIndex("ServiceID");

                    b.ToTable("DetailServices");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Invoice", b =>
                {
                    b.Property<string>("BookingID");

                    b.Property<DateTime>("Invoice_Date");

                    b.Property<double>("Invoice_Total");

                    b.Property<string>("User");

                    b.HasKey("BookingID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Service", b =>
                {
                    b.Property<string>("ServiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<string>("Type");

                    b.Property<string>("Unit");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CDCNPM_Final.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<string>("Status");

                    b.Property<string>("Type");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Booking", b =>
                {
                    b.HasOne("CDCNPM_Final.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.DetailService", b =>
                {
                    b.HasOne("CDCNPM_FInal.Models.Booking", "Booking")
                        .WithMany("DetailServices")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CDCNPM_FInal.Models.Service", "Service")
                        .WithMany("DetailServices")
                        .HasForeignKey("ServiceID");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Invoice", b =>
                {
                    b.HasOne("CDCNPM_FInal.Models.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("CDCNPM_FInal.Models.Invoice", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
