// <auto-generated />
using System;
using CDCNPM_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDCNPM_FInal.Migrations
{
    [DbContext(typeof(KaraokeContext))]
    [Migration("20191003134649_B")]
    partial class B
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDCNPM_FInal.Models.Booking", b =>
                {
                    b.Property<string>("BookingID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CusName");

                    b.Property<string>("CusPhone");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("EndTime");

                    b.Property<double>("PreMoney");

                    b.Property<int?>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("Status");

                    b.Property<double>("Total");

                    b.Property<string>("Username");

                    b.HasKey("BookingID");

                    b.HasIndex("RoomID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.DetailService", b =>
                {
                    b.Property<string>("BookingID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingID1");

                    b.Property<string>("ServiceID");

                    b.HasKey("BookingID");

                    b.HasIndex("BookingID1");

                    b.HasIndex("ServiceID");

                    b.ToTable("DetailServices");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Invoice_Date");

                    b.Property<double>("Invoice_Total");

                    b.Property<string>("User");

                    b.HasKey("InvoiceID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Service", b =>
                {
                    b.Property<string>("ServiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<string>("Unit");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CDCNPM_Final.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<string>("Status");

                    b.Property<string>("Type");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.Booking", b =>
                {
                    b.HasOne("CDCNPM_Final.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("CDCNPM_FInal.Models.DetailService", b =>
                {
                    b.HasOne("CDCNPM_FInal.Models.Booking", "Booking")
                        .WithMany("DetailServices")
                        .HasForeignKey("BookingID1");

                    b.HasOne("CDCNPM_FInal.Models.Service", "Service")
                        .WithMany("DetailServices")
                        .HasForeignKey("ServiceID");
                });
#pragma warning restore 612, 618
        }
    }
}
